name: Release Bottles
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Conty
      run: |
        # Install dwarfs
        #wget -q "$(curl -Ls https://api.github.com/repos/mhx/dwarfs/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*linux.*x86_64.*xz$" | head -1)" &&
        #tar fx ./dwarfs*xz &&
        #sudo mv ./dwarfs*/bin/* /usr/bin/ &&
        #sudo mv ./dwarfs*/sbin/* /usr/sbin/ &&
        #sudo rsync -av ./dwarfs*/share/man* /usr/share/man/ || exit 1
        # Create Conty
        chmod +x create-arch-bootstrap.sh create-conty.sh
        sudo ./create-arch-bootstrap.sh && ./create-conty.sh
        
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: continuous-bottles
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true

    - uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "continuous-bottles"

    - uses: softprops/action-gh-release@v1
      with:
        files: ./conty.sh*
        prerelease: false
        draft: false
        tag_name: continuous-bottles
        name: Bottles
